{
  "save": "/om2/user/ehoseini/MyData/miniBERTa_training/miniBERTa_100m_v2/gpt2/checkpoints_8/",
  "load": "/om2/user/ehoseini/MyData/miniBERTa_training/miniBERTa_100m_v2/gpt2/checkpoints_8/",
  "checkpoint_validation_with_forward_pass": False,
  
  "tensorboard-dir": "tensorboard",
  "log-dir": "logs",
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "miniberta_100M_v2",
  "wandb_group": "gpt2",
}

