# Suggested data paths when using GPT-NeoX locally
{
  #"data-path": "data/enron/enron_text_document",
  #"data-path": "/om/user/ehoseini/MyData/miniBERTa/miniBERTa-1M/miniBERTa-1M_train_text_document",
  # or for weighted datasets: 
  "train-data-paths": ["/om/user/ehoseini/MyData/miniBERTa_v2/miniBERTa-100M/miniBERTa-100M_train_text_document"],
  "test-data-paths": ["/om/user/ehoseini/MyData/miniBERTa_v2/miniBERTa-100M/miniBERTa-100M_test_text_document"],
  "valid-data-paths": ["/om/user/ehoseini/MyData/miniBERTa_v2/miniBERTa-100M/miniBERTa-100M_validation_text_document"],
  #"train-data-weights": [1.],
  #"test-data-weights": [1.],
  #"valid-data-weights": [1.],

  # If weight_by_num_documents is True, Builds dataset weights from a multinomial distribution over groups of data according to the number of documents in each group. 
  # WARNING: setting this to True will override any user provided weights
  #"weight_by_num_documents": false,
  # "weighted_sampler_alpha": 0.3,

  "vocab-file": "data/gpt2-vocab.json",
  "merge-file": "data/gpt2-merges.txt",

}